= Morfuse

:source-highlighter: highlight.js

ifdef::env-github[]
++++
<p align="center">
  <a href=""https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml"><img src="https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml/badge.svg?branch=main" /></a>
  <a href="""https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml""><img src="https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml/badge.svg?branch=main" /></a>
++++
endif::[]

ifndef::env-github[]
image:https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml/badge.svg?branch=main[link="https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml"]
image:https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml/badge.svg?branch=main[link="https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml"]
endif::[]

== Introduction

Morfuse is a game scripting engine system library, it can parse, compile and interpret script files from Medal of Honor: Allied Assault. This implementation is more optimized towards games in general and not only Medal of Honor.
This script engine was originally derived from a script system called Morpheus, from FAKK2.

== Example

[source,cpp]
----
main:
    local.value = "Hello, world!"
    println local.value
end
----

No documentation, yet but more has to come. Feel free to contribute if you're interested in this script engine!

== General features

* Event system
* Ability to declare a class with events into the script system so it can be used
* Simple entity target list, something like `$entity_name.some_var = 1`
* Can call a script label with parameters and/or retrieve the return value from thread
* Cross-platform

== TODO

* [ ] Documentation and more complete README
* [ ] Implement a module system to bind events/classes into a module (plugins)
* [ ] Ability to add events to, or override from existing classes, like ScriptThread
* [ ] Ability to debug scripts
* [ ] JIT compiler (low priority)
