= Morfuse

:source-highlighter: highlight.js

ifdef::env-github[]
++++
<p align="center">
  <a href=""https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml"><img src="https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml/badge.svg?branch=main" /></a>
  <a href="""https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml""><img src="https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml/badge.svg?branch=main" /></a>
++++
endif::[]

ifndef::env-github[]
image:https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml/badge.svg?branch=main[link="https://github.com/morfuse/morfuse/actions/workflows/cmake-linux.yml"]
image:https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml/badge.svg?branch=main[link="https://github.com/morfuse/morfuse/actions/workflows/cmake-windows.yml"]
endif::[]

== Introduction

Morfuse is a scripting engine library: it has its own script language. It is a script engine inspired from Ritual's ÜberTools for Quake III and Medal of Honor: Allied Assault (it can parse scripts from the last one). This script engine targets games primarily.

== Requirements

=== Windows

- Winflexbison (https://github.com/lexxmark/winflexbison)
- CMake (and any compiler)

=== Linux

- Flex and Bison
- CMake (and any compiler)

== Example

[source,cpp]
----
main:
    local.value = "Hello, world!"
    println local.value
end
----

There is no documentation yet but it would be nice to have one. Feel free to contribute if you're interested in this script engine!

== General features

Those are obvious but still worth mentioning:

* Cross-platform (Linux, Windows, x86, x64, ARM, PowerPC, etc...)
* Ability to create classes and methods to be used by scripts
* Pausable/Resumable threads
* Dynamic variables
* Script can be executed with parameters through C++ code, C++ code can easily retrieve return values from thread
* Target list, something like `$entity_name.some_var = 1`

== TODO

Full list of things to do here: https://github.com/morfuse/morfuse/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement